services:
  devcontainer:
    container_name: jt-health-dev-container
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ..:/app

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ../api
    ports:
      - 8080:8080